[theme]
primaryColor = "#4682B4"             # SteelBlue
backgroundColor = "#F5F5F5"          # WhiteSmoke
secondaryBackgroundColor = "#D3D3D3" # LightGray
textColor = "#000000"                # Black
